### PR TITLE
Lollipop

### PR DESCRIPTION
**Pull request by aashrairavooru**
Things done
1)Removed support v4,not needed comes with supportv7 by default
2)Moved to play-services-base since you guys are using only gcm and google analytics using only the base branch should do will reduce the apk size and memory by a lot(this only works with play services version 6.5+)
3)Added proguard rules, will help a lot in removing unused code from libraries and repo itself(enable minify for the same)
Note:Did my best to figure out the rules for the libraries but would still suggest make sure everything is working fine after enabling proguard

Files to look into:
VITacademics-for-Android/vitinfo2/build.gradle
VITacademics-for-Android/vitinfo2/proguard-rules.pro

### CODE REVIEW

**Comment by sreeram-boyapati** [comment]
@aashrairavooru 

1. Code raised  FileNotFoundException  while running `./gradlew assemble -S -q*`. check the build logs.
Execution failed for task ':vitinfo2:proguardDebug'.

**Comment by aashrairavooru** [comment]
Sorry for the late response
Hey is it possible to get the full stacktrace i am not able to compile as the i don't have  vitinfo2/src/main/java/com/karthikb351/vitinfo2/objects/Secret.java

**Comment by saurabhsjoshi** [comment]
Just make a Secret.java file in the project and put this in

package com.karthikb351.vitinfo2.objects;

public class Secret {
    public static String backup_password = "somestringhere";
}

**Comment by aashrairavooru** [comment]
:vitinfo2:proguardDebug task seems to working fine on my end a stacktrace will help

**Comment by sreeram-boyapati** [comment]
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':vitinfo2:proguardDebug'.

at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)

at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)

at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)

at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)

at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)

at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)

at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)

at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)

at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)

at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)

at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)

at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)

at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)

at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)

at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)

at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)

at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)

at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)

at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)

at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)

at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)

at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)

at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)

at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)

at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)

at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)

at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)

at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)

at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)

at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)

at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)

at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)

at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)

at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)

at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)

at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)

at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)

at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)

at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)

at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)

at org.gradle.launcher.Main.doAction(Main.java:33)

at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:483)

at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)

at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)

at org.gradle.launcher.GradleMain.main(GradleMain.java:23)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:483)

at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)

at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)

at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)

Caused by: org.gradle.internal.UncheckedException: java.io.FileNotFoundException: /home/travis/build/saurabhsjoshi/VITacademics-for-Android/android-sdk-linux/tools/proguard/proguard-android.txt (No such file or directory)

at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:39)

at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:66)

at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)

at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)

at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)

at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)

at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)

at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)

at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)

... 55 more

Caused by: java.io.FileNotFoundException: /home/travis/build/saurabhsjoshi/VITacademics-for-Android/android-sdk-linux/tools/proguard/proguard-android.txt (No such file or directory)

at java.io.FileInputStream.open(Native Method)

at java.io.FileInputStream.<init>(FileInputStream.java:138)

at java.io.FileReader.<init>(FileReader.java:72)

at proguard.FileWordReader.<init>(FileWordReader.java:39)

at proguard.ConfigurationParser.<init>(ConfigurationParser.java:105)

at proguard.gradle.ProGuardTask.getConfiguration(ProGuardTask.java:1137)

at proguard.gradle.ProGuardTask.proguard(ProGuardTask.java:1074)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:483)

at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
```

**Comment by aashrairavooru** [comment]
its weird that proguard didn't come with the android-sdk....anyways download the proguard5.1 from this link http://sourceforge.net/projects/proguard/files/proguard/5.1/ and unpack it in /home/travis/build/saurabhsjoshi/VITacademics-for-Android/android-sdk-linux/tools it should fix this also i recommend you update the android sdk being used in travis.

**Comment by sreeram-boyapati** [comment]
@aashrairavooru Thanks for the PR. @saurabhsjoshi shall add it.
@karthikb351 is making a base_app. check it out, you can contribute to it, 

Are you sure its a sdk issue?

**Comment by aashrairavooru** [comment]
@sreeram-boyapati its a problem i have faced this issue as well i had to manually do it in mine too but i ended up not going that route here and used the proguard in the repo as the default one shouldn't be a problem

Few notes with the proguard:
1)Best to use proguard only in your release builds i didn't have the build config so couldn't create one but you guys should it will give you faster builds for the debug
2)Once proguard is integrated make sure that you test everything and i mean everything i tried my best to put all the rules for the available libraries but there can be problems that can only appear only when you runit

Thanks a lot for the quick replies,and hoping to see a leaner,faster vit academics on android
Cheers

**Comment by sreeram-boyapati** [comment]
@aashrairavooru  its a new branch :P

**Pull request closed without merging**
