### PR TITLE
Lollipop

### PR DESCRIPTION
**Pull request by aashrairavooru**
Removed a few unused libraries and added proguard rules.

Please enable minify in the release build this will greatly reduce the app size and memory consumption due to libraries till the time you guys do cleanup of your code

### CODE REVIEW

**Comment by sreeram-boyapati** [comment]
@saurabhsjoshi  Please lets add that gitignore. 1557 files got changed. its hard to verify what actually changed. 
@aashrairavooru please send a pull request to lollipop. once we feel lollipop is stable and the code is ok. we will take a master backup and push force to master.

**Comment by aneesh-neelam** [comment]
@karthikb351, @sreeram-boyapati: I suggest you clean up the branches.

**Comment by karthikb351** [comment]
Yeah, it's long overdue.

**Comment by aashrairavooru** [comment]
Crap didn't notice the branch i created a pull request for sorry.....will do

**Pull request closed without merging**
